// <auto-generated />
using System;
using BeCleverApi.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeCleverApi.Migrations
{
    [DbContext(typeof(dbContextBeClever))]
    [Migration("20240516141009_UpdateEmployeeControl")]
    partial class UpdateEmployeeControl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BeCleverApi.Models.BusinessLocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("businessLocations");
                });

            modelBuilder.Entity("BeCleverApi.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("BeCleverApi.Models.EmployeeControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Employeeid")
                        .HasColumnType("int");

                    b.Property<int>("businessLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("employeeId")
                        .HasColumnType("int");

                    b.Property<string>("registerType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Employeeid");

                    b.HasIndex("businessLocationId");

                    b.HasIndex("employeeId");

                    b.ToTable("employeecontrol");
                });

            modelBuilder.Entity("BeCleverApi.Models.EmployeeControl", b =>
                {
                    b.HasOne("BeCleverApi.Models.Employee", null)
                        .WithMany("employeeControls")
                        .HasForeignKey("Employeeid");

                    b.HasOne("BeCleverApi.Models.BusinessLocation", "businessLocation")
                        .WithMany()
                        .HasForeignKey("businessLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeCleverApi.Models.Employee", "employee")
                        .WithMany()
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("businessLocation");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("BeCleverApi.Models.Employee", b =>
                {
                    b.Navigation("employeeControls");
                });
#pragma warning restore 612, 618
        }
    }
}
